### ISSUE TITLE
Add markushatvan.com

### ISSUE THREAD

**Issue by mhatvan** [janosh/awesome-svelte-kit#1]
I was able to finish the migration of my not-so-simple-anymore website to SvelteKit just today! 

It showcases a setup with tailwindcss JIT, mdsvex, blog posts with code snippets, contact form with svelte forms lib, RSS feed and sitemap generation, etc. 

Feel free to link to:
https://markushatvan.com
https://github.com/mhatvan/markushatvan.com

**Comment by janosh** [comment]
Cool, looks great! Would you like to submit a PR?
