### ISSUE TITLE
Handle array of authors

### ISSUE THREAD

**Issue by janosh** [janosh/awesome-svelte-kit#34]
The way the `site/` is currently setup assumes the author field in `sites.yml` is a string. A few sites set multiple authors as a string array. Shouldn't be hard to handle, e.g. we could just concatenate authors with `, `.

**Comment by ashalfarhan** [comment]
Can i give it a try ? if there's no one working on this.

**Comment by janosh** [comment]
No one that I know of. :)
Go right ahead!

**Comment by janosh** [comment]
Closed in #35.
