### ISSUE TITLE
Project reproduction without attribution

### ISSUE THREAD

**Issue by spences10** [janosh/awesome-svelte-kit#37]
Hi,

Just a heads up [Uvacoder] has used this code to add to their own profile without attribution.

I have personally blocked this account for doing the same thing to several of my own projects.

This account and a couple of similar ones are doing this to many projects on GitHub.

I have reported this behaviour but nothing seems to have come from it.

[Uvacoder]: https://github.com/Uvacoder/awesome-sveltejs-kit

**Comment by janosh** [comment]
> This account and a couple of similar ones are doing this to many projects on GitHub.

You should see the spooky clones of my old Gatsby blog still making the rounds. 👻 

Seriously though, this project is meant for others to do with as they please so fine by me.

Also, not entirely without attribution from @Uvacoder though a bit oddly placed. 😄 

![Screen Shot 2021-11-02 at 09 26 32](https://user-images.githubusercontent.com/30958850/139820989-bf3d7e5b-32b3-4150-a2f8-7bc723dcd8cd.png)
