### ISSUE TITLE
[Suggestion] snippets.life

### ISSUE THREAD

**Issue by n00ki** [janosh/awesome-svelte-kit#46]
**Hi  :)**
First, I would like to thank you and all other contributors for this amazing resource.

As I was starting to passionately learn SvelteKit, I've built a tiny side project around one simple idea: presenting great life quotes & lessons using code snippets.

This project is entirely based on SveleKit, TailwindCSS & Supabase, and is currently deployed to Vercel (using the great vercel-adapter).

As I'm not entirely sure it would fit this amazing curated list of great projects, I thought it might be more reasonable to offer and wait for your thoughts.

anyway, here's a link:
[snippets.life](https://snippets.life)

Thanks again 😄 
and have a good year!

**Comment by janosh** [comment]
Nice idea. 👍 There are some great quotes by well-known scientists that may make good additions to snippets.life:

1. The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.
    ― Stephen Hawking

2. The first principle is that you must not fool yourself – and you are the easiest person to fool.
   ― Richard Feynman

I think if you extend the site a bit more, it would be great to add it to awesome-svelte-kit.

**Comment by n00ki** [comment]
Thanks @janosh :)
These are great quotes.
Please consider pressing the "submit a snippet" button and add them to the list.
I'd love more people to contribute their own favorite quotes and ideas!

**Comment by janosh** [comment]
>Please consider pressing the "submit a snippet" button and add them to the list.

Not sure how those would best be expressed as pseudo-code, I'm afraid.

**Comment by janosh** [comment]
Closing this as stale. Feel free to reopen with updates.
